[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
GeoStats = "dcc97b0b-8ce5-5539-9008-bb190f959ef6"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
StatsKit = "2cb19f9e-ec4d-5c53-8573-a4542a68d3f0"
