name = "Dissertation"
uuid = "b8e1de93-2f59-4d49-9f31-3c82c2d78f6c"
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
Chain = "8be319e6-bccf-4806-a6f7-6fae938471bc"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
CoordRefSystems = "b46f11dc-f210-4604-bfba-323c1ec968cb"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DotEnv = "4dc1fcf4-5e3b-5448-94ab-0c38ec0385c1"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
GeoIO = "f5a160d5-e41d-4189-8b61-d57781c419e3"
GeoJSON = "61d90e0f-e114-555e-ac52-39dfb47a3ef9"
GeoStats = "dcc97b0b-8ce5-5539-9008-bb190f959ef6"
GeoTables = "e502b557-6362-48c1-8219-d30d308dcdb0"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
LanguageServer = "2b0e0bc5-e4fd-59b4-8912-456d1b03d8d7"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
LoggingExtras = "e6f89c97-d47a-5376-807f-9c37f3926c36"
MLJLinearModels = "6ee0df7b-362f-4a72-a706-9e79364fb692"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Match = "7eb4fadd-790c-5f42-8a69-bfa0b872bfbf"
Meshes = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"
Missings = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"
TableTransforms = "0d432bfd-3ee1-4ac1-886a-39f05cc69a3e"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
BenchmarkTools = "1"
CSV = "0.10"
CairoMakie = "0.12, 0.13"
CategoricalArrays = "0.10"
Chain = "0.6"
ColorSchemes = "3"
Colors = "0.12, 0.13"
DataFrames = "1"
Dates = "1.11.0"
Distances = "0.10"
Distributions = "0.25.120"
FileIO = "1"
GLM = "1"
Glob = "1"
HTTP = "1"
IJulia = "1"
JET = "0.9.20"
JSON = "0.21"
JuliaFormatter = "1, 2"
LanguageServer = "4.1.0"
Logging = "1.11.0"
LoggingExtras = "1"
Makie = "0.21, 0.22"
Match = "1, 2"
Meshes = "0.53.7"
Missings = "1"
MultivariateStats = "0.10"
NearestNeighbors = "0.4"
Pkg = "1.11.0"
Printf = "1.11.0"
Revise = "3"
StatsBase = "0.34"
StatsModels = "0.7.6"
TableTransforms = "1"
Unitful = "1"
julia = "1.10, 1.11"
