[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
DotEnv = "4dc1fcf4-5e3b-5448-94ab-0c38ec0385c1"
GeoIO = "f5a160d5-e41d-4189-8b61-d57781c419e3"
GeoStats = "dcc97b0b-8ce5-5539-9008-bb190f959ef6"
GeoTables = "e502b557-6362-48c1-8219-d30d308dcdb0"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Match = "7eb4fadd-790c-5f42-8a69-bfa0b872bfbf"
Meshes = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"
Missings = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
