[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
GeoIO = "f5a160d5-e41d-4189-8b61-d57781c419e3"
GeoStats = "dcc97b0b-8ce5-5539-9008-bb190f959ef6"
GeoTables = "e502b557-6362-48c1-8219-d30d308dcdb0"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
Meshes = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"
Missings = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28"
PointPatterns = "e61b41b6-3414-4803-863f-2b69057479eb"
